[package]
name = "wallpaper-wayland-storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.0.30"
log = "0.4.17"
pretty_env_logger = "0.4.0"
smithay-client-toolkit = "0.16.0"